dist: xenial
language: python
branches:
  only:
    - master
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
install:
  - pip install -e .[dev,charts]
script:
  - pylint penchmark
  - mypy penchmark
  - pytest --disable-pytest-warnings --cov=penchmark penchmark/tests
